# SPDX-License-I$(src)/dentifier: GPL-2.0
#
# Makefile for the Sunplus Geometric Distortion Correction driver.
#

obj-$(CONFIG_VIDEO_SUNPLUS_GDC)	+= gdc.o gdc-buf.o
obj-$(CONFIG_VIDEO_SUNPLUS_GDC_SP7350)	+= gdc-sp7350.o