# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Sunplus MIPI/CSI-RX drivers.
#
sp-vin-objs = sp-core.o sp-dma.o sp-v4l2.o

obj-$(CONFIG_VIDEO_SUNPLUS_Q654_CSI2)       += sp-csi2.o
obj-$(CONFIG_VIDEO_SUNPLUS_Q654_VIN)        += sp-vin.o
