# SPDX-License-Identifier: GPL-2.0-only
sp7350-drm-y := \
	sp7350_drm_drv.o \
	sp7350_drm_plane.o \
	sp7350_drm_dsi.o \
	sp7350_drm_kms.o \
	sp7350_drm_vgem.o \
	sp7350_drm_crtc.o

obj-$(CONFIG_DRM_SP7350) += sp7350-drm.o
