# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Sunplus ISP drivers.
sp-isp-objs = isp.o isp_debugfs.o isp_util.o isp_dbg.o
sp-isp-3dnr-objs = isp_3dnr.o

obj-$(CONFIG_VIDEO_SUNPLUS_SP7350_ISP)		+= sp-isp.o
obj-$(CONFIG_VIDEO_SUNPLUS_SP7350_ISP_3DNR)	+= sp-isp-3dnr.o
