#ifndef REG_STEREO_H
#define REG_STEREO_H

#define SDP_CRC_VERSION

#define STEREO_MODULE_BASE_ADDR    	0xF8C01000
#define SUNPLUS_STEREO_MAX_REG_ADDR	0x800

#define STEREO_CONTROL_0_OFFSET    	0x00000000
#define STEREO_CONTROL_0_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_CONTROL_0_OFFSET)

#define STEREO_FUNC_EN_0_OFFSET    	0x00000004
#define STEREO_FUNC_EN_0_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_FUNC_EN_0_OFFSET)

#define STEREO_CEN_0_OFFSET        	0x00000008
#define STEREO_CEN_0_ADDR          	(STEREO_MODULE_BASE_ADDR + STEREO_CEN_0_OFFSET)

#define STEREO_AGG_C_0_OFFSET      	0x0000000c
#define STEREO_AGG_C_0_ADDR        	(STEREO_MODULE_BASE_ADDR + STEREO_AGG_C_0_OFFSET)

#define STEREO_AGG_C_1_OFFSET      	0x00000010
#define STEREO_AGG_C_1_ADDR        	(STEREO_MODULE_BASE_ADDR + STEREO_AGG_C_1_OFFSET)

#define STEREO_AGG_C_2_OFFSET      	0x00000014
#define STEREO_AGG_C_2_ADDR        	(STEREO_MODULE_BASE_ADDR + STEREO_AGG_C_2_OFFSET)

#define STEREO_AGG_F_0_OFFSET      	0x00000018
#define STEREO_AGG_F_0_ADDR        	(STEREO_MODULE_BASE_ADDR + STEREO_AGG_F_0_OFFSET)

#define STEREO_AGG_F_1_OFFSET      	0x0000001c
#define STEREO_AGG_F_1_ADDR        	(STEREO_MODULE_BASE_ADDR + STEREO_AGG_F_1_OFFSET)

#define STEREO_AGG_F_2_OFFSET      	0x00000020
#define STEREO_AGG_F_2_ADDR        	(STEREO_MODULE_BASE_ADDR + STEREO_AGG_F_2_OFFSET)

#define STEREO_WTA_0_OFFSET        	0x00000024
#define STEREO_WTA_0_ADDR          	(STEREO_MODULE_BASE_ADDR + STEREO_WTA_0_OFFSET)

#define STEREO_EDGE_0_OFFSET       	0x00000028
#define STEREO_EDGE_0_ADDR         	(STEREO_MODULE_BASE_ADDR + STEREO_EDGE_0_OFFSET)

#define STEREO_TOF_FUSION_0_OFFSET 	0x0000002c
#define STEREO_TOF_FUSION_0_ADDR   	(STEREO_MODULE_BASE_ADDR + STEREO_TOF_FUSION_0_OFFSET)

#define STEREO_TOF_FUSION_1_OFFSET 	0x00000030
#define STEREO_TOF_FUSION_1_ADDR   	(STEREO_MODULE_BASE_ADDR + STEREO_TOF_FUSION_1_OFFSET)

#define STEREO_TOF_FUSION_2_OFFSET 	0x00000034
#define STEREO_TOF_FUSION_2_ADDR   	(STEREO_MODULE_BASE_ADDR + STEREO_TOF_FUSION_2_OFFSET)

#define STEREO_TOF_FUSION_3_OFFSET 	0x00000038
#define STEREO_TOF_FUSION_3_ADDR   	(STEREO_MODULE_BASE_ADDR + STEREO_TOF_FUSION_3_OFFSET)

#define STEREO_TOF_FUSION_4_OFFSET 	0x0000003c
#define STEREO_TOF_FUSION_4_ADDR   	(STEREO_MODULE_BASE_ADDR + STEREO_TOF_FUSION_4_OFFSET)

#define STEREO_OUT_FMT_0_OFFSET    	0x00000040
#define STEREO_OUT_FMT_0_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_OUT_FMT_0_OFFSET)

#define STEREO_OUT_FMT_1_OFFSET    	0x00000044
#define STEREO_OUT_FMT_1_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_OUT_FMT_1_OFFSET)

#define STEREO_OC_0_OFFSET         	0x00000100
#define STEREO_OC_0_ADDR           	(STEREO_MODULE_BASE_ADDR + STEREO_OC_0_OFFSET)

#define STEREO_OC_1_OFFSET         	0x00000104
#define STEREO_OC_1_ADDR           	(STEREO_MODULE_BASE_ADDR + STEREO_OC_1_OFFSET)

#define STEREO_OC_2_OFFSET         	0x00000108
#define STEREO_OC_2_ADDR           	(STEREO_MODULE_BASE_ADDR + STEREO_OC_2_OFFSET)

#define STEREO_OC_3_OFFSET         	0x0000010c
#define STEREO_OC_3_ADDR           	(STEREO_MODULE_BASE_ADDR + STEREO_OC_3_OFFSET)

#define STEREO_OC_4_OFFSET         	0x00000110
#define STEREO_OC_4_ADDR           	(STEREO_MODULE_BASE_ADDR + STEREO_OC_4_OFFSET)

#define STEREO_OC_5_OFFSET         	0x00000114
#define STEREO_OC_5_ADDR           	(STEREO_MODULE_BASE_ADDR + STEREO_OC_5_OFFSET)

#define STEREO_HF_0_OFFSET         	0x00000118
#define STEREO_HF_0_ADDR           	(STEREO_MODULE_BASE_ADDR + STEREO_HF_0_OFFSET)

#define STEREO_HF_1_OFFSET         	0x00000130
#define STEREO_HF_1_ADDR           	(STEREO_MODULE_BASE_ADDR + STEREO_HF_1_OFFSET)

#define STEREO_HF_DIF_00_OFFSET    	0x00000134
#define STEREO_HF_DIF_00_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_HF_DIF_00_OFFSET)

#define STEREO_HF_DIF_01_OFFSET    	0x00000138
#define STEREO_HF_DIF_01_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_HF_DIF_01_OFFSET)

#define STEREO_HF_DIF_02_OFFSET    	0x0000013c
#define STEREO_HF_DIF_02_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_HF_DIF_02_OFFSET)

#define STEREO_HF_DIF_03_OFFSET    	0x00000140
#define STEREO_HF_DIF_03_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_HF_DIF_03_OFFSET)

#define STEREO_HF_DIF_04_OFFSET    	0x00000144
#define STEREO_HF_DIF_04_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_HF_DIF_04_OFFSET)

#define STEREO_HF_DIF_05_OFFSET    	0x00000148
#define STEREO_HF_DIF_05_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_HF_DIF_05_OFFSET)

#define STEREO_HF_DIF_06_OFFSET    	0x0000014c
#define STEREO_HF_DIF_06_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_HF_DIF_06_OFFSET)

#define STEREO_HF_DIF_07_OFFSET    	0x00000150
#define STEREO_HF_DIF_07_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_HF_DIF_07_OFFSET)

#define STEREO_HF_DIF_08_OFFSET    	0x00000154
#define STEREO_HF_DIF_08_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_HF_DIF_08_OFFSET)

#define STEREO_HF_DIF_09_OFFSET    	0x00000158
#define STEREO_HF_DIF_09_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_HF_DIF_09_OFFSET)

#define STEREO_HF_DIF_10_OFFSET    	0x0000015c
#define STEREO_HF_DIF_10_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_HF_DIF_10_OFFSET)

#define STEREO_HF_DIF_11_OFFSET    	0x00000160
#define STEREO_HF_DIF_11_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_HF_DIF_11_OFFSET)

#define STEREO_HF_DIF_12_OFFSET    	0x00000164
#define STEREO_HF_DIF_12_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_HF_DIF_12_OFFSET)

#define STEREO_HF_DIF_13_OFFSET    	0x00000168
#define STEREO_HF_DIF_13_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_HF_DIF_13_OFFSET)

#define STEREO_HF_DIF_14_OFFSET    	0x0000016c
#define STEREO_HF_DIF_14_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_HF_DIF_14_OFFSET)

#define STEREO_HF_DIF_15_OFFSET    	0x00000170
#define STEREO_HF_DIF_15_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_HF_DIF_15_OFFSET)

#define STEREO_CONF_WT_0_OFFSET    	0x00000174
#define STEREO_CONF_WT_0_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_CONF_WT_0_OFFSET)

#define STEREO_CONF_WT_1_OFFSET    	0x00000178
#define STEREO_CONF_WT_1_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_CONF_WT_1_OFFSET)

#define STEREO_CONF_WT_2_OFFSET    	0x0000017c
#define STEREO_CONF_WT_2_ADDR      	(STEREO_MODULE_BASE_ADDR + STEREO_CONF_WT_2_OFFSET)

#define STEREO_RHO_AD_000_OFFSET   	0x00000200
#define STEREO_RHO_AD_000_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_000_OFFSET)

#define STEREO_RHO_AD_001_OFFSET   	0x00000204
#define STEREO_RHO_AD_001_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_001_OFFSET)

#define STEREO_RHO_AD_002_OFFSET   	0x00000208
#define STEREO_RHO_AD_002_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_002_OFFSET)

#define STEREO_RHO_AD_003_OFFSET   	0x0000020c
#define STEREO_RHO_AD_003_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_003_OFFSET)

#define STEREO_RHO_AD_004_OFFSET   	0x00000210
#define STEREO_RHO_AD_004_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_004_OFFSET)

#define STEREO_RHO_AD_005_OFFSET   	0x00000214
#define STEREO_RHO_AD_005_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_005_OFFSET)

#define STEREO_RHO_AD_006_OFFSET   	0x00000218
#define STEREO_RHO_AD_006_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_006_OFFSET)

#define STEREO_RHO_AD_007_OFFSET   	0x0000021c
#define STEREO_RHO_AD_007_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_007_OFFSET)

#define STEREO_RHO_AD_008_OFFSET   	0x00000220
#define STEREO_RHO_AD_008_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_008_OFFSET)

#define STEREO_RHO_AD_009_OFFSET   	0x00000224
#define STEREO_RHO_AD_009_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_009_OFFSET)

#define STEREO_RHO_AD_010_OFFSET   	0x00000228
#define STEREO_RHO_AD_010_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_010_OFFSET)

#define STEREO_RHO_AD_011_OFFSET   	0x0000022c
#define STEREO_RHO_AD_011_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_011_OFFSET)

#define STEREO_RHO_AD_012_OFFSET   	0x00000230
#define STEREO_RHO_AD_012_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_012_OFFSET)

#define STEREO_RHO_AD_013_OFFSET   	0x00000234
#define STEREO_RHO_AD_013_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_013_OFFSET)

#define STEREO_RHO_AD_014_OFFSET   	0x00000238
#define STEREO_RHO_AD_014_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_014_OFFSET)

#define STEREO_RHO_AD_015_OFFSET   	0x0000023c
#define STEREO_RHO_AD_015_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_015_OFFSET)

#define STEREO_RHO_AD_016_OFFSET   	0x00000240
#define STEREO_RHO_AD_016_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_016_OFFSET)

#define STEREO_RHO_AD_017_OFFSET   	0x00000244
#define STEREO_RHO_AD_017_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_017_OFFSET)

#define STEREO_RHO_AD_018_OFFSET   	0x00000248
#define STEREO_RHO_AD_018_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_018_OFFSET)

#define STEREO_RHO_AD_019_OFFSET   	0x0000024c
#define STEREO_RHO_AD_019_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_019_OFFSET)

#define STEREO_RHO_AD_020_OFFSET   	0x00000250
#define STEREO_RHO_AD_020_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_020_OFFSET)

#define STEREO_RHO_AD_021_OFFSET   	0x00000254
#define STEREO_RHO_AD_021_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_021_OFFSET)

#define STEREO_RHO_AD_022_OFFSET   	0x00000258
#define STEREO_RHO_AD_022_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_022_OFFSET)

#define STEREO_RHO_AD_023_OFFSET   	0x0000025c
#define STEREO_RHO_AD_023_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_023_OFFSET)

#define STEREO_RHO_AD_024_OFFSET   	0x00000260
#define STEREO_RHO_AD_024_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_024_OFFSET)

#define STEREO_RHO_AD_025_OFFSET   	0x00000264
#define STEREO_RHO_AD_025_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_025_OFFSET)

#define STEREO_RHO_AD_026_OFFSET   	0x00000268
#define STEREO_RHO_AD_026_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_026_OFFSET)

#define STEREO_RHO_AD_027_OFFSET   	0x0000026c
#define STEREO_RHO_AD_027_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_027_OFFSET)

#define STEREO_RHO_AD_028_OFFSET   	0x00000270
#define STEREO_RHO_AD_028_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_028_OFFSET)

#define STEREO_RHO_AD_029_OFFSET   	0x00000274
#define STEREO_RHO_AD_029_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_029_OFFSET)

#define STEREO_RHO_AD_030_OFFSET   	0x00000278
#define STEREO_RHO_AD_030_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_030_OFFSET)

#define STEREO_RHO_AD_031_OFFSET   	0x0000027c
#define STEREO_RHO_AD_031_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_031_OFFSET)

#define STEREO_RHO_AD_032_OFFSET   	0x00000280
#define STEREO_RHO_AD_032_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_032_OFFSET)

#define STEREO_RHO_AD_033_OFFSET   	0x00000284
#define STEREO_RHO_AD_033_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_033_OFFSET)

#define STEREO_RHO_AD_034_OFFSET   	0x00000288
#define STEREO_RHO_AD_034_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_034_OFFSET)

#define STEREO_RHO_AD_035_OFFSET   	0x0000028c
#define STEREO_RHO_AD_035_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_035_OFFSET)

#define STEREO_RHO_AD_036_OFFSET   	0x00000290
#define STEREO_RHO_AD_036_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_036_OFFSET)

#define STEREO_RHO_AD_037_OFFSET   	0x00000294
#define STEREO_RHO_AD_037_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_037_OFFSET)

#define STEREO_RHO_AD_038_OFFSET   	0x00000298
#define STEREO_RHO_AD_038_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_038_OFFSET)

#define STEREO_RHO_AD_039_OFFSET   	0x0000029c
#define STEREO_RHO_AD_039_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_039_OFFSET)

#define STEREO_RHO_AD_040_OFFSET   	0x000002a0
#define STEREO_RHO_AD_040_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_040_OFFSET)

#define STEREO_RHO_AD_041_OFFSET   	0x000002a4
#define STEREO_RHO_AD_041_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_041_OFFSET)

#define STEREO_RHO_AD_042_OFFSET   	0x000002a8
#define STEREO_RHO_AD_042_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_042_OFFSET)

#define STEREO_RHO_AD_043_OFFSET   	0x000002ac
#define STEREO_RHO_AD_043_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_043_OFFSET)

#define STEREO_RHO_AD_044_OFFSET   	0x000002b0
#define STEREO_RHO_AD_044_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_044_OFFSET)

#define STEREO_RHO_AD_045_OFFSET   	0x000002b4
#define STEREO_RHO_AD_045_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_045_OFFSET)

#define STEREO_RHO_AD_046_OFFSET   	0x000002b8
#define STEREO_RHO_AD_046_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_046_OFFSET)

#define STEREO_RHO_AD_047_OFFSET   	0x000002bc
#define STEREO_RHO_AD_047_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_047_OFFSET)

#define STEREO_RHO_AD_048_OFFSET   	0x000002c0
#define STEREO_RHO_AD_048_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_048_OFFSET)

#define STEREO_RHO_AD_049_OFFSET   	0x000002c4
#define STEREO_RHO_AD_049_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_049_OFFSET)

#define STEREO_RHO_AD_050_OFFSET   	0x000002c8
#define STEREO_RHO_AD_050_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_050_OFFSET)

#define STEREO_RHO_AD_051_OFFSET   	0x000002cc
#define STEREO_RHO_AD_051_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_051_OFFSET)

#define STEREO_RHO_AD_052_OFFSET   	0x000002d0
#define STEREO_RHO_AD_052_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_052_OFFSET)

#define STEREO_RHO_AD_053_OFFSET   	0x000002d4
#define STEREO_RHO_AD_053_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_053_OFFSET)

#define STEREO_RHO_AD_054_OFFSET   	0x000002d8
#define STEREO_RHO_AD_054_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_054_OFFSET)

#define STEREO_RHO_AD_055_OFFSET   	0x000002dc
#define STEREO_RHO_AD_055_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_055_OFFSET)

#define STEREO_RHO_AD_056_OFFSET   	0x000002e0
#define STEREO_RHO_AD_056_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_056_OFFSET)

#define STEREO_RHO_AD_057_OFFSET   	0x000002e4
#define STEREO_RHO_AD_057_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_057_OFFSET)

#define STEREO_RHO_AD_058_OFFSET   	0x000002e8
#define STEREO_RHO_AD_058_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_058_OFFSET)

#define STEREO_RHO_AD_059_OFFSET   	0x000002ec
#define STEREO_RHO_AD_059_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_059_OFFSET)

#define STEREO_RHO_AD_060_OFFSET   	0x000002f0
#define STEREO_RHO_AD_060_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_060_OFFSET)

#define STEREO_RHO_AD_061_OFFSET   	0x000002f4
#define STEREO_RHO_AD_061_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_061_OFFSET)

#define STEREO_RHO_AD_062_OFFSET   	0x000002f8
#define STEREO_RHO_AD_062_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_062_OFFSET)

#define STEREO_RHO_AD_063_OFFSET   	0x000002fc
#define STEREO_RHO_AD_063_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_063_OFFSET)

#define STEREO_RHO_AD_064_OFFSET   	0x00000300
#define STEREO_RHO_AD_064_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_064_OFFSET)

#define STEREO_RHO_AD_065_OFFSET   	0x00000304
#define STEREO_RHO_AD_065_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_065_OFFSET)

#define STEREO_RHO_AD_066_OFFSET   	0x00000308
#define STEREO_RHO_AD_066_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_066_OFFSET)

#define STEREO_RHO_AD_067_OFFSET   	0x0000030c
#define STEREO_RHO_AD_067_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_067_OFFSET)

#define STEREO_RHO_AD_068_OFFSET   	0x00000310
#define STEREO_RHO_AD_068_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_068_OFFSET)

#define STEREO_RHO_AD_069_OFFSET   	0x00000314
#define STEREO_RHO_AD_069_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_069_OFFSET)

#define STEREO_RHO_AD_070_OFFSET   	0x00000318
#define STEREO_RHO_AD_070_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_070_OFFSET)

#define STEREO_RHO_AD_071_OFFSET   	0x0000031c
#define STEREO_RHO_AD_071_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_071_OFFSET)

#define STEREO_RHO_AD_072_OFFSET   	0x00000320
#define STEREO_RHO_AD_072_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_072_OFFSET)

#define STEREO_RHO_AD_073_OFFSET   	0x00000324
#define STEREO_RHO_AD_073_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_073_OFFSET)

#define STEREO_RHO_AD_074_OFFSET   	0x00000328
#define STEREO_RHO_AD_074_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_074_OFFSET)

#define STEREO_RHO_AD_075_OFFSET   	0x0000032c
#define STEREO_RHO_AD_075_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_075_OFFSET)

#define STEREO_RHO_AD_076_OFFSET   	0x00000330
#define STEREO_RHO_AD_076_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_076_OFFSET)

#define STEREO_RHO_AD_077_OFFSET   	0x00000334
#define STEREO_RHO_AD_077_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_077_OFFSET)

#define STEREO_RHO_AD_078_OFFSET   	0x00000338
#define STEREO_RHO_AD_078_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_078_OFFSET)

#define STEREO_RHO_AD_079_OFFSET   	0x0000033c
#define STEREO_RHO_AD_079_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_079_OFFSET)

#define STEREO_RHO_AD_080_OFFSET   	0x00000340
#define STEREO_RHO_AD_080_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_080_OFFSET)

#define STEREO_RHO_AD_081_OFFSET   	0x00000344
#define STEREO_RHO_AD_081_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_081_OFFSET)

#define STEREO_RHO_AD_082_OFFSET   	0x00000348
#define STEREO_RHO_AD_082_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_082_OFFSET)

#define STEREO_RHO_AD_083_OFFSET   	0x0000034c
#define STEREO_RHO_AD_083_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_083_OFFSET)

#define STEREO_RHO_AD_084_OFFSET   	0x00000350
#define STEREO_RHO_AD_084_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_084_OFFSET)

#define STEREO_RHO_AD_085_OFFSET   	0x00000354
#define STEREO_RHO_AD_085_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_085_OFFSET)

#define STEREO_RHO_AD_086_OFFSET   	0x00000358
#define STEREO_RHO_AD_086_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_086_OFFSET)

#define STEREO_RHO_AD_087_OFFSET   	0x0000035c
#define STEREO_RHO_AD_087_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_087_OFFSET)

#define STEREO_RHO_AD_088_OFFSET   	0x00000360
#define STEREO_RHO_AD_088_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_088_OFFSET)

#define STEREO_RHO_AD_089_OFFSET   	0x00000364
#define STEREO_RHO_AD_089_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_089_OFFSET)

#define STEREO_RHO_AD_090_OFFSET   	0x00000368
#define STEREO_RHO_AD_090_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_090_OFFSET)

#define STEREO_RHO_AD_091_OFFSET   	0x0000036c
#define STEREO_RHO_AD_091_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_091_OFFSET)

#define STEREO_RHO_AD_092_OFFSET   	0x00000370
#define STEREO_RHO_AD_092_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_092_OFFSET)

#define STEREO_RHO_AD_093_OFFSET   	0x00000374
#define STEREO_RHO_AD_093_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_093_OFFSET)

#define STEREO_RHO_AD_094_OFFSET   	0x00000378
#define STEREO_RHO_AD_094_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_094_OFFSET)

#define STEREO_RHO_AD_095_OFFSET   	0x0000037c
#define STEREO_RHO_AD_095_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_095_OFFSET)

#define STEREO_RHO_AD_096_OFFSET   	0x00000380
#define STEREO_RHO_AD_096_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_096_OFFSET)

#define STEREO_RHO_AD_097_OFFSET   	0x00000384
#define STEREO_RHO_AD_097_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_097_OFFSET)

#define STEREO_RHO_AD_098_OFFSET   	0x00000388
#define STEREO_RHO_AD_098_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_098_OFFSET)

#define STEREO_RHO_AD_099_OFFSET   	0x0000038c
#define STEREO_RHO_AD_099_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_099_OFFSET)

#define STEREO_RHO_AD_100_OFFSET   	0x00000390
#define STEREO_RHO_AD_100_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_100_OFFSET)

#define STEREO_RHO_AD_101_OFFSET   	0x00000394
#define STEREO_RHO_AD_101_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_101_OFFSET)

#define STEREO_RHO_AD_102_OFFSET   	0x00000398
#define STEREO_RHO_AD_102_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_102_OFFSET)

#define STEREO_RHO_AD_103_OFFSET   	0x0000039c
#define STEREO_RHO_AD_103_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_103_OFFSET)

#define STEREO_RHO_AD_104_OFFSET   	0x000003a0
#define STEREO_RHO_AD_104_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_104_OFFSET)

#define STEREO_RHO_AD_105_OFFSET   	0x000003a4
#define STEREO_RHO_AD_105_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_105_OFFSET)

#define STEREO_RHO_AD_106_OFFSET   	0x000003a8
#define STEREO_RHO_AD_106_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_106_OFFSET)

#define STEREO_RHO_AD_107_OFFSET   	0x000003ac
#define STEREO_RHO_AD_107_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_107_OFFSET)

#define STEREO_RHO_AD_108_OFFSET   	0x000003b0
#define STEREO_RHO_AD_108_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_108_OFFSET)

#define STEREO_RHO_AD_109_OFFSET   	0x000003b4
#define STEREO_RHO_AD_109_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_109_OFFSET)

#define STEREO_RHO_AD_110_OFFSET   	0x000003b8
#define STEREO_RHO_AD_110_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_110_OFFSET)

#define STEREO_RHO_AD_111_OFFSET   	0x000003bc
#define STEREO_RHO_AD_111_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_111_OFFSET)

#define STEREO_RHO_AD_112_OFFSET   	0x000003c0
#define STEREO_RHO_AD_112_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_112_OFFSET)

#define STEREO_RHO_AD_113_OFFSET   	0x000003c4
#define STEREO_RHO_AD_113_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_113_OFFSET)

#define STEREO_RHO_AD_114_OFFSET   	0x000003c8
#define STEREO_RHO_AD_114_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_114_OFFSET)

#define STEREO_RHO_AD_115_OFFSET   	0x000003cc
#define STEREO_RHO_AD_115_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_115_OFFSET)

#define STEREO_RHO_AD_116_OFFSET   	0x000003d0
#define STEREO_RHO_AD_116_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_116_OFFSET)

#define STEREO_RHO_AD_117_OFFSET   	0x000003d4
#define STEREO_RHO_AD_117_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_117_OFFSET)

#define STEREO_RHO_AD_118_OFFSET   	0x000003d8
#define STEREO_RHO_AD_118_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_118_OFFSET)

#define STEREO_RHO_AD_119_OFFSET   	0x000003dc
#define STEREO_RHO_AD_119_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_119_OFFSET)

#define STEREO_RHO_AD_120_OFFSET   	0x000003e0
#define STEREO_RHO_AD_120_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_120_OFFSET)

#define STEREO_RHO_AD_121_OFFSET   	0x000003e4
#define STEREO_RHO_AD_121_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_121_OFFSET)

#define STEREO_RHO_AD_122_OFFSET   	0x000003e8
#define STEREO_RHO_AD_122_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_122_OFFSET)

#define STEREO_RHO_AD_123_OFFSET   	0x000003ec
#define STEREO_RHO_AD_123_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_123_OFFSET)

#define STEREO_RHO_AD_124_OFFSET   	0x000003f0
#define STEREO_RHO_AD_124_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_124_OFFSET)

#define STEREO_RHO_AD_125_OFFSET   	0x000003f4
#define STEREO_RHO_AD_125_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_125_OFFSET)

#define STEREO_RHO_AD_126_OFFSET   	0x000003f8
#define STEREO_RHO_AD_126_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_126_OFFSET)

#define STEREO_RHO_AD_127_OFFSET   	0x000003fc
#define STEREO_RHO_AD_127_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_AD_127_OFFSET)

#define STEREO_RHO_CEN_00_OFFSET   	0x00000400
#define STEREO_RHO_CEN_00_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_00_OFFSET)

#define STEREO_RHO_CEN_01_OFFSET   	0x00000404
#define STEREO_RHO_CEN_01_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_01_OFFSET)

#define STEREO_RHO_CEN_02_OFFSET   	0x00000408
#define STEREO_RHO_CEN_02_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_02_OFFSET)

#define STEREO_RHO_CEN_03_OFFSET   	0x0000040c
#define STEREO_RHO_CEN_03_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_03_OFFSET)

#define STEREO_RHO_CEN_04_OFFSET   	0x00000410
#define STEREO_RHO_CEN_04_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_04_OFFSET)

#define STEREO_RHO_CEN_05_OFFSET   	0x00000414
#define STEREO_RHO_CEN_05_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_05_OFFSET)

#define STEREO_RHO_CEN_06_OFFSET   	0x00000418
#define STEREO_RHO_CEN_06_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_06_OFFSET)

#define STEREO_RHO_CEN_07_OFFSET   	0x0000041c
#define STEREO_RHO_CEN_07_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_07_OFFSET)

#define STEREO_RHO_CEN_08_OFFSET   	0x00000420
#define STEREO_RHO_CEN_08_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_08_OFFSET)

#define STEREO_RHO_CEN_09_OFFSET   	0x00000424
#define STEREO_RHO_CEN_09_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_09_OFFSET)

#define STEREO_RHO_CEN_10_OFFSET   	0x00000428
#define STEREO_RHO_CEN_10_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_10_OFFSET)

#define STEREO_RHO_CEN_11_OFFSET   	0x0000042c
#define STEREO_RHO_CEN_11_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_11_OFFSET)

#define STEREO_RHO_CEN_12_OFFSET   	0x00000430
#define STEREO_RHO_CEN_12_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_12_OFFSET)

#define STEREO_RHO_CEN_13_OFFSET   	0x00000434
#define STEREO_RHO_CEN_13_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_13_OFFSET)

#define STEREO_RHO_CEN_14_OFFSET   	0x00000438
#define STEREO_RHO_CEN_14_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_14_OFFSET)

#define STEREO_RHO_CEN_15_OFFSET   	0x0000043c
#define STEREO_RHO_CEN_15_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_15_OFFSET)

#define STEREO_RHO_CEN_16_OFFSET   	0x00000440
#define STEREO_RHO_CEN_16_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_16_OFFSET)

#define STEREO_RHO_CEN_17_OFFSET   	0x00000444
#define STEREO_RHO_CEN_17_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_17_OFFSET)

#define STEREO_RHO_CEN_18_OFFSET   	0x00000448
#define STEREO_RHO_CEN_18_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_18_OFFSET)

#define STEREO_RHO_CEN_19_OFFSET   	0x0000044c
#define STEREO_RHO_CEN_19_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_19_OFFSET)

#define STEREO_RHO_CEN_20_OFFSET   	0x00000450
#define STEREO_RHO_CEN_20_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_20_OFFSET)

#define STEREO_RHO_CEN_21_OFFSET   	0x00000454
#define STEREO_RHO_CEN_21_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_21_OFFSET)

#define STEREO_RHO_CEN_22_OFFSET   	0x00000458
#define STEREO_RHO_CEN_22_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_22_OFFSET)

#define STEREO_RHO_CEN_23_OFFSET   	0x0000045c
#define STEREO_RHO_CEN_23_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_23_OFFSET)

#define STEREO_RHO_CEN_24_OFFSET   	0x00000460
#define STEREO_RHO_CEN_24_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_24_OFFSET)

#define STEREO_RHO_CEN_25_OFFSET   	0x00000464
#define STEREO_RHO_CEN_25_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_25_OFFSET)

#define STEREO_RHO_CEN_26_OFFSET   	0x00000468
#define STEREO_RHO_CEN_26_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_26_OFFSET)

#define STEREO_RHO_CEN_27_OFFSET   	0x0000046c
#define STEREO_RHO_CEN_27_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_27_OFFSET)

#define STEREO_RHO_CEN_28_OFFSET   	0x00000470
#define STEREO_RHO_CEN_28_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_28_OFFSET)

#define STEREO_RHO_CEN_29_OFFSET   	0x00000474
#define STEREO_RHO_CEN_29_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_29_OFFSET)

#define STEREO_RHO_CEN_30_OFFSET   	0x00000478
#define STEREO_RHO_CEN_30_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_30_OFFSET)

#define STEREO_RHO_CEN_31_OFFSET   	0x0000047c
#define STEREO_RHO_CEN_31_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_31_OFFSET)

#define STEREO_RHO_CEN_32_OFFSET   	0x00000480
#define STEREO_RHO_CEN_32_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_32_OFFSET)

#define STEREO_RHO_CEN_33_OFFSET   	0x00000484
#define STEREO_RHO_CEN_33_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_33_OFFSET)

#define STEREO_RHO_CEN_34_OFFSET   	0x00000488
#define STEREO_RHO_CEN_34_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_34_OFFSET)

#define STEREO_RHO_CEN_35_OFFSET   	0x0000048c
#define STEREO_RHO_CEN_35_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_35_OFFSET)

#define STEREO_RHO_CEN_36_OFFSET   	0x00000490
#define STEREO_RHO_CEN_36_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_36_OFFSET)

#define STEREO_RHO_CEN_37_OFFSET   	0x00000494
#define STEREO_RHO_CEN_37_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_37_OFFSET)

#define STEREO_RHO_CEN_38_OFFSET   	0x00000498
#define STEREO_RHO_CEN_38_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_38_OFFSET)

#define STEREO_RHO_CEN_39_OFFSET   	0x0000049c
#define STEREO_RHO_CEN_39_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_39_OFFSET)

#define STEREO_RHO_CEN_40_OFFSET   	0x000004a0
#define STEREO_RHO_CEN_40_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_40_OFFSET)

#define STEREO_RHO_CEN_41_OFFSET   	0x000004a4
#define STEREO_RHO_CEN_41_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_41_OFFSET)

#define STEREO_RHO_CEN_42_OFFSET   	0x000004a8
#define STEREO_RHO_CEN_42_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_42_OFFSET)

#define STEREO_RHO_CEN_43_OFFSET   	0x000004ac
#define STEREO_RHO_CEN_43_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_43_OFFSET)

#define STEREO_RHO_CEN_44_OFFSET   	0x000004b0
#define STEREO_RHO_CEN_44_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_44_OFFSET)

#define STEREO_RHO_CEN_45_OFFSET   	0x000004b4
#define STEREO_RHO_CEN_45_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_45_OFFSET)

#define STEREO_RHO_CEN_46_OFFSET   	0x000004b8
#define STEREO_RHO_CEN_46_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_46_OFFSET)

#define STEREO_RHO_CEN_47_OFFSET   	0x000004bc
#define STEREO_RHO_CEN_47_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_47_OFFSET)

#define STEREO_RHO_CEN_48_OFFSET   	0x000004c0
#define STEREO_RHO_CEN_48_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_48_OFFSET)

#define STEREO_RHO_CEN_49_OFFSET   	0x000004c4
#define STEREO_RHO_CEN_49_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_49_OFFSET)

#define STEREO_RHO_CEN_50_OFFSET   	0x000004c8
#define STEREO_RHO_CEN_50_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_50_OFFSET)

#define STEREO_RHO_CEN_51_OFFSET   	0x000004cc
#define STEREO_RHO_CEN_51_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_51_OFFSET)

#define STEREO_RHO_CEN_52_OFFSET   	0x000004d0
#define STEREO_RHO_CEN_52_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_52_OFFSET)

#define STEREO_RHO_CEN_53_OFFSET   	0x000004d4
#define STEREO_RHO_CEN_53_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_53_OFFSET)

#define STEREO_RHO_CEN_54_OFFSET   	0x000004d8
#define STEREO_RHO_CEN_54_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_54_OFFSET)

#define STEREO_RHO_CEN_55_OFFSET   	0x000004dc
#define STEREO_RHO_CEN_55_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_55_OFFSET)

#define STEREO_RHO_CEN_56_OFFSET   	0x000004e0
#define STEREO_RHO_CEN_56_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_56_OFFSET)

#define STEREO_RHO_CEN_57_OFFSET   	0x000004e4
#define STEREO_RHO_CEN_57_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_57_OFFSET)

#define STEREO_RHO_CEN_58_OFFSET   	0x000004e8
#define STEREO_RHO_CEN_58_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_58_OFFSET)

#define STEREO_RHO_CEN_59_OFFSET   	0x000004ec
#define STEREO_RHO_CEN_59_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_59_OFFSET)

#define STEREO_RHO_CEN_60_OFFSET   	0x000004f0
#define STEREO_RHO_CEN_60_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_60_OFFSET)

#define STEREO_RHO_CEN_61_OFFSET   	0x000004f4
#define STEREO_RHO_CEN_61_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_61_OFFSET)

#define STEREO_RHO_CEN_62_OFFSET   	0x000004f8
#define STEREO_RHO_CEN_62_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_62_OFFSET)

#define STEREO_RHO_CEN_63_OFFSET   	0x000004fc
#define STEREO_RHO_CEN_63_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RHO_CEN_63_OFFSET)

#define STEREO_SDP_HW_INFO_OFFSET  	0x00000500
#define STEREO_SDP_HW_INFO_ADDR    	(STEREO_MODULE_BASE_ADDR + STEREO_SDP_HW_INFO_OFFSET)

#define STEREO_FRAME_START_OFFSET  	0x00000504
#define STEREO_FRAME_START_ADDR    	(STEREO_MODULE_BASE_ADDR + STEREO_FRAME_START_OFFSET)

#define STEREO_SOFT_RESET_OFFSET   	0x00000508
#define STEREO_SOFT_RESET_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_SOFT_RESET_OFFSET)

#define STEREO_SDP_IRQ_MASK_OFFSET 	0x0000050c
#define STEREO_SDP_IRQ_MASK_ADDR   	(STEREO_MODULE_BASE_ADDR + STEREO_SDP_IRQ_MASK_OFFSET)

#define STEREO_SDP_FRM_STATUS_OFFSET	0x00000510
#define STEREO_SDP_FRM_STATUS_ADDR 	(STEREO_MODULE_BASE_ADDR + STEREO_SDP_FRM_STATUS_OFFSET)

#define STEREO_SDP_ADDR_STATUS_OFFSET	0x00000514
#define STEREO_SDP_ADDR_STATUS_ADDR	(STEREO_MODULE_BASE_ADDR + STEREO_SDP_ADDR_STATUS_OFFSET)

#define STEREO_LF_R_CFG_0_OFFSET   	0x00000518
#define STEREO_LF_R_CFG_0_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_LF_R_CFG_0_OFFSET)

#define STEREO_LF_R_ADDR_LO_OFFSET 	0x0000051c
#define STEREO_LF_R_ADDR_LO_ADDR   	(STEREO_MODULE_BASE_ADDR + STEREO_LF_R_ADDR_LO_OFFSET)

#define STEREO_LF_R_ADDR_HI_OFFSET 	0x00000520
#define STEREO_LF_R_ADDR_HI_ADDR   	(STEREO_MODULE_BASE_ADDR + STEREO_LF_R_ADDR_HI_OFFSET)

#define STEREO_RF_R_CFG_0_OFFSET   	0x00000524
#define STEREO_RF_R_CFG_0_ADDR     	(STEREO_MODULE_BASE_ADDR + STEREO_RF_R_CFG_0_OFFSET)

#define STEREO_RF_R_ADDR_LO_OFFSET 	0x00000528
#define STEREO_RF_R_ADDR_LO_ADDR   	(STEREO_MODULE_BASE_ADDR + STEREO_RF_R_ADDR_LO_OFFSET)

#define STEREO_RF_R_ADDR_HI_OFFSET 	0x0000052c
#define STEREO_RF_R_ADDR_HI_ADDR   	(STEREO_MODULE_BASE_ADDR + STEREO_RF_R_ADDR_HI_OFFSET)

#define STEREO_TOFD_R_CFG_0_OFFSET 	0x00000530
#define STEREO_TOFD_R_CFG_0_ADDR   	(STEREO_MODULE_BASE_ADDR + STEREO_TOFD_R_CFG_0_OFFSET)

#define STEREO_TOFD_R_ADDR_LO_OFFSET	0x00000534
#define STEREO_TOFD_R_ADDR_LO_ADDR 	(STEREO_MODULE_BASE_ADDR + STEREO_TOFD_R_ADDR_LO_OFFSET)

#define STEREO_TOFD_R_ADDR_HI_OFFSET	0x00000538
#define STEREO_TOFD_R_ADDR_HI_ADDR 	(STEREO_MODULE_BASE_ADDR + STEREO_TOFD_R_ADDR_HI_OFFSET)

#define STEREO_TOFC_R_CFG_0_OFFSET 	0x0000053c
#define STEREO_TOFC_R_CFG_0_ADDR   	(STEREO_MODULE_BASE_ADDR + STEREO_TOFC_R_CFG_0_OFFSET)

#define STEREO_TOFC_R_ADDR_LO_OFFSET	0x00000540
#define STEREO_TOFC_R_ADDR_LO_ADDR 	(STEREO_MODULE_BASE_ADDR + STEREO_TOFC_R_ADDR_LO_OFFSET)

#define STEREO_TOFC_R_ADDR_HI_OFFSET	0x00000544
#define STEREO_TOFC_R_ADDR_HI_ADDR 	(STEREO_MODULE_BASE_ADDR + STEREO_TOFC_R_ADDR_HI_OFFSET)

#define STEREO_DEPTH_W_CFG_0_OFFSET	0x00000548
#define STEREO_DEPTH_W_CFG_0_ADDR  	(STEREO_MODULE_BASE_ADDR + STEREO_DEPTH_W_CFG_0_OFFSET)

#define STEREO_DEPTH_W_ADDR_LO_OFFSET	0x0000054c
#define STEREO_DEPTH_W_ADDR_LO_ADDR	(STEREO_MODULE_BASE_ADDR + STEREO_DEPTH_W_ADDR_LO_OFFSET)

#define STEREO_DEPTH_W_ADDR_HI_OFFSET	0x00000550
#define STEREO_DEPTH_W_ADDR_HI_ADDR	(STEREO_MODULE_BASE_ADDR + STEREO_DEPTH_W_ADDR_HI_OFFSET)

#define STEREO_L_IMG_FRAM_CFG_0_OFFSET	0x00000554
#define STEREO_L_IMG_FRAM_CFG_0_ADDR 	(STEREO_MODULE_BASE_ADDR + STEREO_L_IMG_FRAM_CFG_0_OFFSET)

#define STEREO_L_IMG_FRAM_CFG_1_OFFSET	0x00000558
#define STEREO_L_IMG_FRAM_CFG_1_ADDR 	(STEREO_MODULE_BASE_ADDR + STEREO_L_IMG_FRAM_CFG_1_OFFSET)

#define STEREO_L_IMG_FRAM_CFG_2_OFFSET	0x0000055c
#define STEREO_L_IMG_FRAM_CFG_2_ADDR 	(STEREO_MODULE_BASE_ADDR + STEREO_L_IMG_FRAM_CFG_2_OFFSET)

#define STEREO_L_IMG_HSGR_OFFSET     	0x00000560
#define STEREO_L_IMG_HSGR_ADDR       	(STEREO_MODULE_BASE_ADDR + STEREO_L_IMG_HSGR_OFFSET)

#define STEREO_L_IMG_VSGR_OFFSET     	0x00000564
#define STEREO_L_IMG_VSGR_ADDR       	(STEREO_MODULE_BASE_ADDR + STEREO_L_IMG_VSGR_OFFSET)

#define STEREO_TOF_FRAM_CFG_0_OFFSET	0x00000568
#define STEREO_TOF_FRAM_CFG_0_ADDR 	(STEREO_MODULE_BASE_ADDR + STEREO_TOF_FRAM_CFG_0_OFFSET)

#define STEREO_TOF_FRAM_CFG_1_OFFSET	0x0000056c
#define STEREO_TOF_FRAM_CFG_1_ADDR 	(STEREO_MODULE_BASE_ADDR + STEREO_TOF_FRAM_CFG_1_OFFSET)

#define STEREO_TOF_FRAM_CFG_2_OFFSET	0x00000570
#define STEREO_TOF_FRAM_CFG_2_ADDR 	(STEREO_MODULE_BASE_ADDR + STEREO_TOF_FRAM_CFG_2_OFFSET)

#define STEREO_TOF_HSGR_OFFSET     	0x00000574
#define STEREO_TOF_HSGR_ADDR       	(STEREO_MODULE_BASE_ADDR + STEREO_TOF_HSGR_OFFSET)

#define STEREO_TOF_VSGR_OFFSET     	0x00000578
#define STEREO_TOF_VSGR_ADDR       	(STEREO_MODULE_BASE_ADDR + STEREO_TOF_VSGR_OFFSET)

#define STEREO_DIS_FRAM_CFG_0_OFFSET	0x0000057c
#define STEREO_DIS_FRAM_CFG_0_ADDR 	(STEREO_MODULE_BASE_ADDR + STEREO_DIS_FRAM_CFG_0_OFFSET)

#define STEREO_DIS_FRAM_CFG_1_OFFSET	0x00000580
#define STEREO_DIS_FRAM_CFG_1_ADDR 	(STEREO_MODULE_BASE_ADDR + STEREO_DIS_FRAM_CFG_1_OFFSET)

#define STEREO_DIS_HDSR_OFFSET     	0x00000584
#define STEREO_DIS_HDSR_ADDR       	(STEREO_MODULE_BASE_ADDR + STEREO_DIS_HDSR_OFFSET)

#define STEREO_DIS_VDSR_OFFSET     	0x00000588
#define STEREO_DIS_VDSR_ADDR       	(STEREO_MODULE_BASE_ADDR + STEREO_DIS_VDSR_OFFSET)

#define STEREO_RQOS_CFG_OFFSET     	0x0000058c
#define STEREO_RQOS_CFG_ADDR       	(STEREO_MODULE_BASE_ADDR + STEREO_RQOS_CFG_OFFSET)

#define STEREO_WQOS_CFG_OFFSET     	0x00000590
#define STEREO_WQOS_CFG_ADDR       	(STEREO_MODULE_BASE_ADDR + STEREO_WQOS_CFG_OFFSET)

#ifdef SDP_CRC_VERSION
#define STEREO_RD_CRC_OFFSET       	0x00000594
#define STEREO_RD_CRC_ADDR         	(STEREO_MODULE_BASE_ADDR + STEREO_RD_CRC_OFFSET)

#define STEREO_WR_CRC_OFFSET       	0x00000598
#define STEREO_WR_CRC_ADDR         	(STEREO_MODULE_BASE_ADDR + STEREO_WR_CRC_OFFSET)
#endif

#define STEREO_R_IMG_FRAM_CFG_0_OFFSET	0x0000059c
#define STEREO_R_IMG_FRAM_CFG_0_ADDR 	(STEREO_MODULE_BASE_ADDR + STEREO_R_IMG_FRAM_CFG_0_OFFSET)

#define STEREO_R_IMG_FRAM_CFG_1_OFFSET	0x000005a0
#define STEREO_R_IMG_FRAM_CFG_1_ADDR 	(STEREO_MODULE_BASE_ADDR + STEREO_R_IMG_FRAM_CFG_1_OFFSET)

#define STEREO_R_IMG_FRAM_CFG_2_OFFSET	0x000005a4
#define STEREO_R_IMG_FRAM_CFG_2_ADDR 	(STEREO_MODULE_BASE_ADDR + STEREO_R_IMG_FRAM_CFG_2_OFFSET)

#define STEREO_R_IMG_HSGR_OFFSET     0x000005a8
#define STEREO_R_IMG_HSGR_ADDR       (STEREO_MODULE_BASE_ADDR + STEREO_R_IMG_HSGR_OFFSET)

#define STEREO_R_IMG_VSGR_OFFSET     0x000005ac
#define STEREO_R_IMG_VSGR_ADDR       (STEREO_MODULE_BASE_ADDR + STEREO_R_IMG_VSGR_OFFSET)

#define STEREO_FWRR_CTRL_0_OFFSET  	0x00000c00
#define STEREO_FWRR_CTRL_0_ADDR    	(STEREO_MODULE_BASE_ADDR + STEREO_FWRR_CTRL_0_OFFSET)

#define STEREO_FWRR_CTRL_1_OFFSET  	0x00000c04
#define STEREO_FWRR_CTRL_1_ADDR    	(STEREO_MODULE_BASE_ADDR + STEREO_FWRR_CTRL_1_OFFSET)

#define STEREO_FWRR_STATUS_0_OFFSET	0x00000c08
#define STEREO_FWRR_STATUS_0_ADDR  	(STEREO_MODULE_BASE_ADDR + STEREO_FWRR_STATUS_0_OFFSET)

#define STEREO_FWRR_MEM_ADDR_0_OFFSET	0x00000c0c
#define STEREO_FWRR_MEM_ADDR_0_ADDR	(STEREO_MODULE_BASE_ADDR + STEREO_FWRR_MEM_ADDR_0_OFFSET)

#define STEREO_FWRR_MEM_ADDR_1_OFFSET	0x00000c10
#define STEREO_FWRR_MEM_ADDR_1_ADDR	(STEREO_MODULE_BASE_ADDR + STEREO_FWRR_MEM_ADDR_1_OFFSET)

#define STEREO_RWFR_CTRL_0_OFFSET  	0x00000c14
#define STEREO_RWFR_CTRL_0_ADDR    	(STEREO_MODULE_BASE_ADDR + STEREO_RWFR_CTRL_0_OFFSET)

#define STEREO_RWFR_CTRL_1_OFFSET  	0x00000c18
#define STEREO_RWFR_CTRL_1_ADDR    	(STEREO_MODULE_BASE_ADDR + STEREO_RWFR_CTRL_1_OFFSET)

#define STEREO_RWFR_STATUS_0_OFFSET	0x00000c1c
#define STEREO_RWFR_STATUS_0_ADDR  	(STEREO_MODULE_BASE_ADDR + STEREO_RWFR_STATUS_0_OFFSET)

#define STEREO_RWFR_MEM_ADDR_0_OFFSET	0x00000c20
#define STEREO_RWFR_MEM_ADDR_0_ADDR	(STEREO_MODULE_BASE_ADDR + STEREO_RWFR_MEM_ADDR_0_OFFSET)

#define STEREO_RWFR_MEM_ADDR_1_OFFSET	0x00000c24
#define STEREO_RWFR_MEM_ADDR_1_ADDR	(STEREO_MODULE_BASE_ADDR + STEREO_RWFR_MEM_ADDR_1_OFFSET)

#define STEREO_FWRR_MEM_ADDR_2_OFFSET	0x00000c28
#define STEREO_FWRR_MEM_ADDR_2_ADDR	(STEREO_MODULE_BASE_ADDR + STEREO_FWRR_MEM_ADDR_2_OFFSET)

#define STEREO_FWRR_MEM_ADDR_3_OFFSET	0x00000c2c
#define STEREO_FWRR_MEM_ADDR_3_ADDR	(STEREO_MODULE_BASE_ADDR + STEREO_FWRR_MEM_ADDR_3_OFFSET)

#define STEREO_RWFR_MEM_ADDR_2_OFFSET	0x00000c30
#define STEREO_RWFR_MEM_ADDR_2_ADDR	(STEREO_MODULE_BASE_ADDR + STEREO_RWFR_MEM_ADDR_2_OFFSET)

#define STEREO_RWFR_MEM_ADDR_3_OFFSET	0x00000c34
#define STEREO_RWFR_MEM_ADDR_3_ADDR	(STEREO_MODULE_BASE_ADDR + STEREO_RWFR_MEM_ADDR_3_OFFSET)

#define STEREO_FINAL_ADDR                	STEREO_RWFR_MEM_ADDR_3_ADDR

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_width:13;
		unsigned int reserved0:3;
		unsigned int f_height:13;
		unsigned int reserved1:3;
	};
} STEREO_Control_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_diagonal_search_en:1;
		unsigned int f_prevent_overlap_en:1;
		unsigned int f_tof_fusion_en:1;
		unsigned int f_subpixel_en:1;
		unsigned int f_occlusion_fill_en:1;
		unsigned int f_refinement_en:1;
		unsigned int f_global_occlusion_en_R:1;
		unsigned int f_min_cost_check_en_R:1;
		unsigned int f_median_en_R:1;
		unsigned int f_occlusion_expansion_en_R:1;
		unsigned int f_global_occlusion_en_L:1;
		unsigned int f_min_cost_check_en_L:1;
		unsigned int f_median_en_L:1;
		unsigned int f_occlusion_expansion_en_L:1;
		unsigned int f_fill_background_expand_en:1;
		unsigned int f_bilateral_check_en:1;
		unsigned int f_voting_en:1;
		unsigned int f_reference_left_only_en:1;
		unsigned int f_median_en_HF:1;
		unsigned int f_disparity_smooth_en:1;
		unsigned int f_occlusion_labeling_en:1;
		unsigned int f_sgm_8direction_en:1;
		unsigned int f_thresh_mode:1;
		unsigned int f_depth_out:1;
		unsigned int reserved0:8;
	};
} STEREO_FUNC_EN_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_coarse_census_ignore_th:8;
		unsigned int f_fine_census_ignore_th:8;
		unsigned int f_census_margin:8;
		unsigned int f_keep_band:3;
		unsigned int reserved0:5;
	};
} STEREO_CEN_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_coarse_gradient_th_large:8;
		unsigned int f_coarse_gradient_th_median:8;
		unsigned int f_coarse_gradient_th_small:8;
		unsigned int reserved0:8;
	};
} STEREO_AGG_C_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_coarse_penalty1_large:8;
		unsigned int f_coarse_penalty1_median:8;
		unsigned int f_coarse_penalty1_small:8;
		unsigned int f_coarse_penalty1_other:8;
	};
} STEREO_AGG_C_1_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_coarse_penalty2_large:8;
		unsigned int f_coarse_penalty2_median:8;
		unsigned int f_coarse_penalty2_small:8;
		unsigned int f_coarse_penalty2_other:8;
	};
} STEREO_AGG_C_2_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_fine_gradient_th_large:8;
		unsigned int f_fine_gradient_th_median:8;
		unsigned int f_fine_gradient_th_small:8;
		unsigned int reserved0:8;
	};
} STEREO_AGG_F_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_fine_penalty1_large:8;
		unsigned int f_fine_penalty1_median:8;
		unsigned int f_fine_penalty1_small:8;
		unsigned int f_fine_penalty1_other:8;
	};
} STEREO_AGG_F_1_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_fine_penalty2_large:8;
		unsigned int f_fine_penalty2_median:8;
		unsigned int f_fine_penalty2_small:8;
		unsigned int f_fine_penalty2_other:8;
	};
} STEREO_AGG_F_2_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_wta_smooth_th:8;
		unsigned int f_wta_smooth_wt_0:8;
		unsigned int f_wta_smooth_wt_1:8;
		unsigned int reserved0:8;
	};
} STEREO_WTA_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_edge_gradient_th_strict:8;
		unsigned int reserved0:8;
		unsigned int f_edge_gradient_th_loose:8;
		unsigned int reserved1:8;
	};
} STEREO_EDGE_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_weight_th_low:8;
		unsigned int f_weight_th_high:8;
		unsigned int reserved0:16;
	};
} STEREO_TOF_FUSION_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_bad_depth_penalty:8;
		unsigned int f_low_weight_penalty:8;
		unsigned int f_legal_depth_th:4;
		unsigned int f_selTofConf:8;
		unsigned int reserved0:4;
	};
} STEREO_TOF_FUSION_1_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_legal_depth_cost_0:8;
		unsigned int f_legal_depth_cost_1:8;
		unsigned int f_legal_depth_cost_2:8;
		unsigned int f_legal_depth_cost_3:8;
	};
} STEREO_TOF_FUSION_2_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_legal_depth_cost_4:8;
		unsigned int f_legal_depth_cost_5:8;
		unsigned int f_legal_depth_cost_6:8;
		unsigned int f_legal_depth_cost_7:8;
	};
} STEREO_TOF_FUSION_3_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_legal_depth_cost_8:8;
		unsigned int f_legal_depth_cost_9:8;
		unsigned int reserved0:16;
	};
} STEREO_TOF_FUSION_4_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_FB_val:16;
		unsigned int f_thresh_val:7;
		unsigned int reserved0:9;
	};
} STEREO_OUT_FMT_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_dep_inv_val:13;
		unsigned int f_disp_inv_val:9;
		unsigned int reserved0:10;
	};
} STEREO_OUT_FMT_1_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_global_occlusion_disparity_th_l:8;
		unsigned int f_global_occlusion_disparity_th_r:8;
		unsigned int reserved0:16;
	};
} STEREO_OC_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_consistency_check_th:4;
		unsigned int f_occlusion_labeling_th:4;
		unsigned int reserved0:24;
	};
} STEREO_OC_1_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_min_cost_check_th:8;
		unsigned int reserved0:24;
	};
} STEREO_OC_2_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_ideal_background_th_gt:6;
		unsigned int f_ideal_background_th_lt:6;
		unsigned int f_occlusion_expansion_arm_L:4;
		unsigned int f_occlusion_expansion_arm_R:4;
		unsigned int reserved0:12;
	};
} STEREO_OC_3_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_density_check_th_0:7;
		unsigned int f_density_check_th_1:7;
		unsigned int reserved0:18;
	};
} STEREO_OC_4_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_median_valid_count_th_L:4;
		unsigned int f_median_valid_count_th_R:4;
		unsigned int f_median_mode_L:1;
		unsigned int f_median_mode_R:1;
		unsigned int reserved0:22;
	};
} STEREO_OC_5_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_vote_valid_pctg:8;
		unsigned int f_vote_major_pctg:8;
		unsigned int f_vote_valid_th:8;
		unsigned int reserved0:8;
	};
} STEREO_HF_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_median_valid_count_th_HF:4;
		unsigned int reserved0:28;
	};
} STEREO_HF_1_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_allow_dif_000:4;
		unsigned int f_allow_dif_001:4;
		unsigned int f_allow_dif_002:4;
		unsigned int f_allow_dif_003:4;
		unsigned int f_allow_dif_004:4;
		unsigned int f_allow_dif_005:4;
		unsigned int f_allow_dif_006:4;
		unsigned int f_allow_dif_007:4;
	};
} STEREO_HF_DIF_00_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_allow_dif_008:4;
		unsigned int f_allow_dif_009:4;
		unsigned int f_allow_dif_010:4;
		unsigned int f_allow_dif_011:4;
		unsigned int f_allow_dif_012:4;
		unsigned int f_allow_dif_013:4;
		unsigned int f_allow_dif_014:4;
		unsigned int f_allow_dif_015:4;
	};
} STEREO_HF_DIF_01_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_allow_dif_016:4;
		unsigned int f_allow_dif_017:4;
		unsigned int f_allow_dif_018:4;
		unsigned int f_allow_dif_019:4;
		unsigned int f_allow_dif_020:4;
		unsigned int f_allow_dif_021:4;
		unsigned int f_allow_dif_022:4;
		unsigned int f_allow_dif_023:4;
	};
} STEREO_HF_DIF_02_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_allow_dif_024:4;
		unsigned int f_allow_dif_025:4;
		unsigned int f_allow_dif_026:4;
		unsigned int f_allow_dif_027:4;
		unsigned int f_allow_dif_028:4;
		unsigned int f_allow_dif_029:4;
		unsigned int f_allow_dif_030:4;
		unsigned int f_allow_dif_031:4;
	};
} STEREO_HF_DIF_03_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_allow_dif_032:4;
		unsigned int f_allow_dif_033:4;
		unsigned int f_allow_dif_034:4;
		unsigned int f_allow_dif_035:4;
		unsigned int f_allow_dif_036:4;
		unsigned int f_allow_dif_037:4;
		unsigned int f_allow_dif_038:4;
		unsigned int f_allow_dif_039:4;
	};
} STEREO_HF_DIF_04_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_allow_dif_040:4;
		unsigned int f_allow_dif_041:4;
		unsigned int f_allow_dif_042:4;
		unsigned int f_allow_dif_043:4;
		unsigned int f_allow_dif_044:4;
		unsigned int f_allow_dif_045:4;
		unsigned int f_allow_dif_046:4;
		unsigned int f_allow_dif_047:4;
	};
} STEREO_HF_DIF_05_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_allow_dif_048:4;
		unsigned int f_allow_dif_049:4;
		unsigned int f_allow_dif_050:4;
		unsigned int f_allow_dif_051:4;
		unsigned int f_allow_dif_052:4;
		unsigned int f_allow_dif_053:4;
		unsigned int f_allow_dif_054:4;
		unsigned int f_allow_dif_055:4;
	};
} STEREO_HF_DIF_06_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_allow_dif_056:4;
		unsigned int f_allow_dif_057:4;
		unsigned int f_allow_dif_058:4;
		unsigned int f_allow_dif_059:4;
		unsigned int f_allow_dif_060:4;
		unsigned int f_allow_dif_061:4;
		unsigned int f_allow_dif_062:4;
		unsigned int f_allow_dif_063:4;
	};
} STEREO_HF_DIF_07_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_allow_dif_064:4;
		unsigned int f_allow_dif_065:4;
		unsigned int f_allow_dif_066:4;
		unsigned int f_allow_dif_067:4;
		unsigned int f_allow_dif_068:4;
		unsigned int f_allow_dif_069:4;
		unsigned int f_allow_dif_070:4;
		unsigned int f_allow_dif_071:4;
	};
} STEREO_HF_DIF_08_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_allow_dif_072:4;
		unsigned int f_allow_dif_073:4;
		unsigned int f_allow_dif_074:4;
		unsigned int f_allow_dif_075:4;
		unsigned int f_allow_dif_076:4;
		unsigned int f_allow_dif_077:4;
		unsigned int f_allow_dif_078:4;
		unsigned int f_allow_dif_079:4;
	};
} STEREO_HF_DIF_09_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_allow_dif_080:4;
		unsigned int f_allow_dif_081:4;
		unsigned int f_allow_dif_082:4;
		unsigned int f_allow_dif_083:4;
		unsigned int f_allow_dif_084:4;
		unsigned int f_allow_dif_085:4;
		unsigned int f_allow_dif_086:4;
		unsigned int f_allow_dif_087:4;
	};
} STEREO_HF_DIF_10_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_allow_dif_088:4;
		unsigned int f_allow_dif_089:4;
		unsigned int f_allow_dif_090:4;
		unsigned int f_allow_dif_091:4;
		unsigned int f_allow_dif_092:4;
		unsigned int f_allow_dif_093:4;
		unsigned int f_allow_dif_094:4;
		unsigned int f_allow_dif_095:4;
	};
} STEREO_HF_DIF_11_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_allow_dif_096:4;
		unsigned int f_allow_dif_097:4;
		unsigned int f_allow_dif_098:4;
		unsigned int f_allow_dif_099:4;
		unsigned int f_allow_dif_100:4;
		unsigned int f_allow_dif_101:4;
		unsigned int f_allow_dif_102:4;
		unsigned int f_allow_dif_103:4;
	};
} STEREO_HF_DIF_12_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_allow_dif_104:4;
		unsigned int f_allow_dif_105:4;
		unsigned int f_allow_dif_106:4;
		unsigned int f_allow_dif_107:4;
		unsigned int f_allow_dif_108:4;
		unsigned int f_allow_dif_109:4;
		unsigned int f_allow_dif_110:4;
		unsigned int f_allow_dif_111:4;
	};
} STEREO_HF_DIF_13_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_allow_dif_112:4;
		unsigned int f_allow_dif_113:4;
		unsigned int f_allow_dif_114:4;
		unsigned int f_allow_dif_115:4;
		unsigned int f_allow_dif_116:4;
		unsigned int f_allow_dif_117:4;
		unsigned int f_allow_dif_118:4;
		unsigned int f_allow_dif_119:4;
	};
} STEREO_HF_DIF_14_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_allow_dif_120:4;
		unsigned int f_allow_dif_121:4;
		unsigned int f_allow_dif_122:4;
		unsigned int f_allow_dif_123:4;
		unsigned int f_allow_dif_124:4;
		unsigned int f_allow_dif_125:4;
		unsigned int f_allow_dif_126:4;
		unsigned int f_allow_dif_127:4;
	};
} STEREO_HF_DIF_15_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_wtConfSgm0:8;
		unsigned int f_wtConfSgm1:8;
		unsigned int f_wtConfMincost:8;
		unsigned int reserved0:8;
	};
} STEREO_CONF_WT_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_wtConfGlobOcc:8;
		unsigned int f_wtConfConsis:8;
		unsigned int f_wtConfMed:8;
		unsigned int reserved0:8;
	};
} STEREO_CONF_WT_1_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_wtConfOccExp:8;
		unsigned int f_wtConfBilat:8;
		unsigned int f_holeFillConf:8;
		unsigned int reserved0:8;
	};
} STEREO_CONF_WT_2_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_000:16;
		unsigned int f_rho_abs_dif_001:16;
	};
} STEREO_RHO_AD_000_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_002:16;
		unsigned int f_rho_abs_dif_003:16;
	};
} STEREO_RHO_AD_001_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_004:16;
		unsigned int f_rho_abs_dif_005:16;
	};
} STEREO_RHO_AD_002_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_006:16;
		unsigned int f_rho_abs_dif_007:16;
	};
} STEREO_RHO_AD_003_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_008:16;
		unsigned int f_rho_abs_dif_009:16;
	};
} STEREO_RHO_AD_004_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_010:16;
		unsigned int f_rho_abs_dif_011:16;
	};
} STEREO_RHO_AD_005_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_012:16;
		unsigned int f_rho_abs_dif_013:16;
	};
} STEREO_RHO_AD_006_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_014:16;
		unsigned int f_rho_abs_dif_015:16;
	};
} STEREO_RHO_AD_007_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_016:16;
		unsigned int f_rho_abs_dif_017:16;
	};
} STEREO_RHO_AD_008_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_018:16;
		unsigned int f_rho_abs_dif_019:16;
	};
} STEREO_RHO_AD_009_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_020:16;
		unsigned int f_rho_abs_dif_021:16;
	};
} STEREO_RHO_AD_010_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_022:16;
		unsigned int f_rho_abs_dif_023:16;
	};
} STEREO_RHO_AD_011_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_024:16;
		unsigned int f_rho_abs_dif_025:16;
	};
} STEREO_RHO_AD_012_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_026:16;
		unsigned int f_rho_abs_dif_027:16;
	};
} STEREO_RHO_AD_013_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_028:16;
		unsigned int f_rho_abs_dif_029:16;
	};
} STEREO_RHO_AD_014_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_030:16;
		unsigned int f_rho_abs_dif_031:16;
	};
} STEREO_RHO_AD_015_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_032:16;
		unsigned int f_rho_abs_dif_033:16;
	};
} STEREO_RHO_AD_016_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_034:16;
		unsigned int f_rho_abs_dif_035:16;
	};
} STEREO_RHO_AD_017_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_036:16;
		unsigned int f_rho_abs_dif_037:16;
	};
} STEREO_RHO_AD_018_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_038:16;
		unsigned int f_rho_abs_dif_039:16;
	};
} STEREO_RHO_AD_019_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_040:16;
		unsigned int f_rho_abs_dif_041:16;
	};
} STEREO_RHO_AD_020_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_042:16;
		unsigned int f_rho_abs_dif_043:16;
	};
} STEREO_RHO_AD_021_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_044:16;
		unsigned int f_rho_abs_dif_045:16;
	};
} STEREO_RHO_AD_022_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_046:16;
		unsigned int f_rho_abs_dif_047:16;
	};
} STEREO_RHO_AD_023_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_048:16;
		unsigned int f_rho_abs_dif_049:16;
	};
} STEREO_RHO_AD_024_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_050:16;
		unsigned int f_rho_abs_dif_051:16;
	};
} STEREO_RHO_AD_025_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_052:16;
		unsigned int f_rho_abs_dif_053:16;
	};
} STEREO_RHO_AD_026_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_054:16;
		unsigned int f_rho_abs_dif_055:16;
	};
} STEREO_RHO_AD_027_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_056:16;
		unsigned int f_rho_abs_dif_057:16;
	};
} STEREO_RHO_AD_028_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_058:16;
		unsigned int f_rho_abs_dif_059:16;
	};
} STEREO_RHO_AD_029_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_060:16;
		unsigned int f_rho_abs_dif_061:16;
	};
} STEREO_RHO_AD_030_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_062:16;
		unsigned int f_rho_abs_dif_063:16;
	};
} STEREO_RHO_AD_031_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_064:16;
		unsigned int f_rho_abs_dif_065:16;
	};
} STEREO_RHO_AD_032_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_066:16;
		unsigned int f_rho_abs_dif_067:16;
	};
} STEREO_RHO_AD_033_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_068:16;
		unsigned int f_rho_abs_dif_069:16;
	};
} STEREO_RHO_AD_034_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_070:16;
		unsigned int f_rho_abs_dif_071:16;
	};
} STEREO_RHO_AD_035_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_072:16;
		unsigned int f_rho_abs_dif_073:16;
	};
} STEREO_RHO_AD_036_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_074:16;
		unsigned int f_rho_abs_dif_075:16;
	};
} STEREO_RHO_AD_037_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_076:16;
		unsigned int f_rho_abs_dif_077:16;
	};
} STEREO_RHO_AD_038_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_078:16;
		unsigned int f_rho_abs_dif_079:16;
	};
} STEREO_RHO_AD_039_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_080:16;
		unsigned int f_rho_abs_dif_081:16;
	};
} STEREO_RHO_AD_040_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_082:16;
		unsigned int f_rho_abs_dif_083:16;
	};
} STEREO_RHO_AD_041_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_084:16;
		unsigned int f_rho_abs_dif_085:16;
	};
} STEREO_RHO_AD_042_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_086:16;
		unsigned int f_rho_abs_dif_087:16;
	};
} STEREO_RHO_AD_043_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_088:16;
		unsigned int f_rho_abs_dif_089:16;
	};
} STEREO_RHO_AD_044_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_090:16;
		unsigned int f_rho_abs_dif_091:16;
	};
} STEREO_RHO_AD_045_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_092:16;
		unsigned int f_rho_abs_dif_093:16;
	};
} STEREO_RHO_AD_046_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_094:16;
		unsigned int f_rho_abs_dif_095:16;
	};
} STEREO_RHO_AD_047_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_096:16;
		unsigned int f_rho_abs_dif_097:16;
	};
} STEREO_RHO_AD_048_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_098:16;
		unsigned int f_rho_abs_dif_099:16;
	};
} STEREO_RHO_AD_049_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_100:16;
		unsigned int f_rho_abs_dif_101:16;
	};
} STEREO_RHO_AD_050_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_102:16;
		unsigned int f_rho_abs_dif_103:16;
	};
} STEREO_RHO_AD_051_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_104:16;
		unsigned int f_rho_abs_dif_105:16;
	};
} STEREO_RHO_AD_052_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_106:16;
		unsigned int f_rho_abs_dif_107:16;
	};
} STEREO_RHO_AD_053_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_108:16;
		unsigned int f_rho_abs_dif_109:16;
	};
} STEREO_RHO_AD_054_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_110:16;
		unsigned int f_rho_abs_dif_111:16;
	};
} STEREO_RHO_AD_055_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_112:16;
		unsigned int f_rho_abs_dif_113:16;
	};
} STEREO_RHO_AD_056_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_114:16;
		unsigned int f_rho_abs_dif_115:16;
	};
} STEREO_RHO_AD_057_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_116:16;
		unsigned int f_rho_abs_dif_117:16;
	};
} STEREO_RHO_AD_058_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_118:16;
		unsigned int f_rho_abs_dif_119:16;
	};
} STEREO_RHO_AD_059_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_120:16;
		unsigned int f_rho_abs_dif_121:16;
	};
} STEREO_RHO_AD_060_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_122:16;
		unsigned int f_rho_abs_dif_123:16;
	};
} STEREO_RHO_AD_061_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_124:16;
		unsigned int f_rho_abs_dif_125:16;
	};
} STEREO_RHO_AD_062_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_126:16;
		unsigned int f_rho_abs_dif_127:16;
	};
} STEREO_RHO_AD_063_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_128:16;
		unsigned int f_rho_abs_dif_129:16;
	};
} STEREO_RHO_AD_064_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_130:16;
		unsigned int f_rho_abs_dif_131:16;
	};
} STEREO_RHO_AD_065_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_132:16;
		unsigned int f_rho_abs_dif_133:16;
	};
} STEREO_RHO_AD_066_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_134:16;
		unsigned int f_rho_abs_dif_135:16;
	};
} STEREO_RHO_AD_067_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_136:16;
		unsigned int f_rho_abs_dif_137:16;
	};
} STEREO_RHO_AD_068_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_138:16;
		unsigned int f_rho_abs_dif_139:16;
	};
} STEREO_RHO_AD_069_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_140:16;
		unsigned int f_rho_abs_dif_141:16;
	};
} STEREO_RHO_AD_070_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_142:16;
		unsigned int f_rho_abs_dif_143:16;
	};
} STEREO_RHO_AD_071_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_144:16;
		unsigned int f_rho_abs_dif_145:16;
	};
} STEREO_RHO_AD_072_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_146:16;
		unsigned int f_rho_abs_dif_147:16;
	};
} STEREO_RHO_AD_073_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_148:16;
		unsigned int f_rho_abs_dif_149:16;
	};
} STEREO_RHO_AD_074_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_150:16;
		unsigned int f_rho_abs_dif_151:16;
	};
} STEREO_RHO_AD_075_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_152:16;
		unsigned int f_rho_abs_dif_153:16;
	};
} STEREO_RHO_AD_076_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_154:16;
		unsigned int f_rho_abs_dif_155:16;
	};
} STEREO_RHO_AD_077_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_156:16;
		unsigned int f_rho_abs_dif_157:16;
	};
} STEREO_RHO_AD_078_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_158:16;
		unsigned int f_rho_abs_dif_159:16;
	};
} STEREO_RHO_AD_079_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_160:16;
		unsigned int f_rho_abs_dif_161:16;
	};
} STEREO_RHO_AD_080_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_162:16;
		unsigned int f_rho_abs_dif_163:16;
	};
} STEREO_RHO_AD_081_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_164:16;
		unsigned int f_rho_abs_dif_165:16;
	};
} STEREO_RHO_AD_082_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_166:16;
		unsigned int f_rho_abs_dif_167:16;
	};
} STEREO_RHO_AD_083_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_168:16;
		unsigned int f_rho_abs_dif_169:16;
	};
} STEREO_RHO_AD_084_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_170:16;
		unsigned int f_rho_abs_dif_171:16;
	};
} STEREO_RHO_AD_085_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_172:16;
		unsigned int f_rho_abs_dif_173:16;
	};
} STEREO_RHO_AD_086_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_174:16;
		unsigned int f_rho_abs_dif_175:16;
	};
} STEREO_RHO_AD_087_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_176:16;
		unsigned int f_rho_abs_dif_177:16;
	};
} STEREO_RHO_AD_088_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_178:16;
		unsigned int f_rho_abs_dif_179:16;
	};
} STEREO_RHO_AD_089_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_180:16;
		unsigned int f_rho_abs_dif_181:16;
	};
} STEREO_RHO_AD_090_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_182:16;
		unsigned int f_rho_abs_dif_183:16;
	};
} STEREO_RHO_AD_091_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_184:16;
		unsigned int f_rho_abs_dif_185:16;
	};
} STEREO_RHO_AD_092_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_186:16;
		unsigned int f_rho_abs_dif_187:16;
	};
} STEREO_RHO_AD_093_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_188:16;
		unsigned int f_rho_abs_dif_189:16;
	};
} STEREO_RHO_AD_094_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_190:16;
		unsigned int f_rho_abs_dif_191:16;
	};
} STEREO_RHO_AD_095_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_192:16;
		unsigned int f_rho_abs_dif_193:16;
	};
} STEREO_RHO_AD_096_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_194:16;
		unsigned int f_rho_abs_dif_195:16;
	};
} STEREO_RHO_AD_097_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_196:16;
		unsigned int f_rho_abs_dif_197:16;
	};
} STEREO_RHO_AD_098_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_198:16;
		unsigned int f_rho_abs_dif_199:16;
	};
} STEREO_RHO_AD_099_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_200:16;
		unsigned int f_rho_abs_dif_201:16;
	};
} STEREO_RHO_AD_100_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_202:16;
		unsigned int f_rho_abs_dif_203:16;
	};
} STEREO_RHO_AD_101_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_204:16;
		unsigned int f_rho_abs_dif_205:16;
	};
} STEREO_RHO_AD_102_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_206:16;
		unsigned int f_rho_abs_dif_207:16;
	};
} STEREO_RHO_AD_103_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_208:16;
		unsigned int f_rho_abs_dif_209:16;
	};
} STEREO_RHO_AD_104_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_210:16;
		unsigned int f_rho_abs_dif_211:16;
	};
} STEREO_RHO_AD_105_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_212:16;
		unsigned int f_rho_abs_dif_213:16;
	};
} STEREO_RHO_AD_106_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_214:16;
		unsigned int f_rho_abs_dif_215:16;
	};
} STEREO_RHO_AD_107_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_216:16;
		unsigned int f_rho_abs_dif_217:16;
	};
} STEREO_RHO_AD_108_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_218:16;
		unsigned int f_rho_abs_dif_219:16;
	};
} STEREO_RHO_AD_109_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_220:16;
		unsigned int f_rho_abs_dif_221:16;
	};
} STEREO_RHO_AD_110_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_222:16;
		unsigned int f_rho_abs_dif_223:16;
	};
} STEREO_RHO_AD_111_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_224:16;
		unsigned int f_rho_abs_dif_225:16;
	};
} STEREO_RHO_AD_112_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_226:16;
		unsigned int f_rho_abs_dif_227:16;
	};
} STEREO_RHO_AD_113_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_228:16;
		unsigned int f_rho_abs_dif_229:16;
	};
} STEREO_RHO_AD_114_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_230:16;
		unsigned int f_rho_abs_dif_231:16;
	};
} STEREO_RHO_AD_115_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_232:16;
		unsigned int f_rho_abs_dif_233:16;
	};
} STEREO_RHO_AD_116_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_234:16;
		unsigned int f_rho_abs_dif_235:16;
	};
} STEREO_RHO_AD_117_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_236:16;
		unsigned int f_rho_abs_dif_237:16;
	};
} STEREO_RHO_AD_118_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_238:16;
		unsigned int f_rho_abs_dif_239:16;
	};
} STEREO_RHO_AD_119_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_240:16;
		unsigned int f_rho_abs_dif_241:16;
	};
} STEREO_RHO_AD_120_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_242:16;
		unsigned int f_rho_abs_dif_243:16;
	};
} STEREO_RHO_AD_121_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_244:16;
		unsigned int f_rho_abs_dif_245:16;
	};
} STEREO_RHO_AD_122_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_246:16;
		unsigned int f_rho_abs_dif_247:16;
	};
} STEREO_RHO_AD_123_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_248:16;
		unsigned int f_rho_abs_dif_249:16;
	};
} STEREO_RHO_AD_124_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_250:16;
		unsigned int f_rho_abs_dif_251:16;
	};
} STEREO_RHO_AD_125_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_252:16;
		unsigned int f_rho_abs_dif_253:16;
	};
} STEREO_RHO_AD_126_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_abs_dif_254:16;
		unsigned int f_rho_abs_dif_255:16;
	};
} STEREO_RHO_AD_127_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_000:16;
		unsigned int f_rho_ham_dis_001:16;
	};
} STEREO_RHO_CEN_00_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_002:16;
		unsigned int f_rho_ham_dis_003:16;
	};
} STEREO_RHO_CEN_01_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_004:16;
		unsigned int f_rho_ham_dis_005:16;
	};
} STEREO_RHO_CEN_02_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_006:16;
		unsigned int f_rho_ham_dis_007:16;
	};
} STEREO_RHO_CEN_03_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_008:16;
		unsigned int f_rho_ham_dis_009:16;
	};
} STEREO_RHO_CEN_04_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_010:16;
		unsigned int f_rho_ham_dis_011:16;
	};
} STEREO_RHO_CEN_05_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_012:16;
		unsigned int f_rho_ham_dis_013:16;
	};
} STEREO_RHO_CEN_06_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_014:16;
		unsigned int f_rho_ham_dis_015:16;
	};
} STEREO_RHO_CEN_07_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_016:16;
		unsigned int f_rho_ham_dis_017:16;
	};
} STEREO_RHO_CEN_08_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_018:16;
		unsigned int f_rho_ham_dis_019:16;
	};
} STEREO_RHO_CEN_09_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_020:16;
		unsigned int f_rho_ham_dis_021:16;
	};
} STEREO_RHO_CEN_10_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_022:16;
		unsigned int f_rho_ham_dis_023:16;
	};
} STEREO_RHO_CEN_11_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_024:16;
		unsigned int f_rho_ham_dis_025:16;
	};
} STEREO_RHO_CEN_12_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_026:16;
		unsigned int f_rho_ham_dis_027:16;
	};
} STEREO_RHO_CEN_13_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_028:16;
		unsigned int f_rho_ham_dis_029:16;
	};
} STEREO_RHO_CEN_14_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_030:16;
		unsigned int f_rho_ham_dis_031:16;
	};
} STEREO_RHO_CEN_15_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_032:16;
		unsigned int f_rho_ham_dis_033:16;
	};
} STEREO_RHO_CEN_16_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_034:16;
		unsigned int f_rho_ham_dis_035:16;
	};
} STEREO_RHO_CEN_17_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_036:16;
		unsigned int f_rho_ham_dis_037:16;
	};
} STEREO_RHO_CEN_18_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_038:16;
		unsigned int f_rho_ham_dis_039:16;
	};
} STEREO_RHO_CEN_19_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_040:16;
		unsigned int f_rho_ham_dis_041:16;
	};
} STEREO_RHO_CEN_20_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_042:16;
		unsigned int f_rho_ham_dis_043:16;
	};
} STEREO_RHO_CEN_21_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_044:16;
		unsigned int f_rho_ham_dis_045:16;
	};
} STEREO_RHO_CEN_22_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_046:16;
		unsigned int f_rho_ham_dis_047:16;
	};
} STEREO_RHO_CEN_23_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_048:16;
		unsigned int f_rho_ham_dis_049:16;
	};
} STEREO_RHO_CEN_24_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_050:16;
		unsigned int f_rho_ham_dis_051:16;
	};
} STEREO_RHO_CEN_25_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_052:16;
		unsigned int f_rho_ham_dis_053:16;
	};
} STEREO_RHO_CEN_26_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_054:16;
		unsigned int f_rho_ham_dis_055:16;
	};
} STEREO_RHO_CEN_27_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_056:16;
		unsigned int f_rho_ham_dis_057:16;
	};
} STEREO_RHO_CEN_28_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_058:16;
		unsigned int f_rho_ham_dis_059:16;
	};
} STEREO_RHO_CEN_29_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_060:16;
		unsigned int f_rho_ham_dis_061:16;
	};
} STEREO_RHO_CEN_30_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_062:16;
		unsigned int f_rho_ham_dis_063:16;
	};
} STEREO_RHO_CEN_31_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_064:16;
		unsigned int f_rho_ham_dis_065:16;
	};
} STEREO_RHO_CEN_32_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_066:16;
		unsigned int f_rho_ham_dis_067:16;
	};
} STEREO_RHO_CEN_33_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_068:16;
		unsigned int f_rho_ham_dis_069:16;
	};
} STEREO_RHO_CEN_34_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_070:16;
		unsigned int f_rho_ham_dis_071:16;
	};
} STEREO_RHO_CEN_35_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_072:16;
		unsigned int f_rho_ham_dis_073:16;
	};
} STEREO_RHO_CEN_36_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_074:16;
		unsigned int f_rho_ham_dis_075:16;
	};
} STEREO_RHO_CEN_37_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_076:16;
		unsigned int f_rho_ham_dis_077:16;
	};
} STEREO_RHO_CEN_38_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_078:16;
		unsigned int f_rho_ham_dis_079:16;
	};
} STEREO_RHO_CEN_39_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_080:16;
		unsigned int f_rho_ham_dis_081:16;
	};
} STEREO_RHO_CEN_40_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_082:16;
		unsigned int f_rho_ham_dis_083:16;
	};
} STEREO_RHO_CEN_41_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_084:16;
		unsigned int f_rho_ham_dis_085:16;
	};
} STEREO_RHO_CEN_42_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_086:16;
		unsigned int f_rho_ham_dis_087:16;
	};
} STEREO_RHO_CEN_43_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_088:16;
		unsigned int f_rho_ham_dis_089:16;
	};
} STEREO_RHO_CEN_44_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_090:16;
		unsigned int f_rho_ham_dis_091:16;
	};
} STEREO_RHO_CEN_45_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_092:16;
		unsigned int f_rho_ham_dis_093:16;
	};
} STEREO_RHO_CEN_46_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_094:16;
		unsigned int f_rho_ham_dis_095:16;
	};
} STEREO_RHO_CEN_47_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_096:16;
		unsigned int f_rho_ham_dis_097:16;
	};
} STEREO_RHO_CEN_48_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_098:16;
		unsigned int f_rho_ham_dis_099:16;
	};
} STEREO_RHO_CEN_49_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_100:16;
		unsigned int f_rho_ham_dis_101:16;
	};
} STEREO_RHO_CEN_50_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_102:16;
		unsigned int f_rho_ham_dis_103:16;
	};
} STEREO_RHO_CEN_51_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_104:16;
		unsigned int f_rho_ham_dis_105:16;
	};
} STEREO_RHO_CEN_52_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_106:16;
		unsigned int f_rho_ham_dis_107:16;
	};
} STEREO_RHO_CEN_53_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_108:16;
		unsigned int f_rho_ham_dis_109:16;
	};
} STEREO_RHO_CEN_54_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_110:16;
		unsigned int f_rho_ham_dis_111:16;
	};
} STEREO_RHO_CEN_55_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_112:16;
		unsigned int f_rho_ham_dis_113:16;
	};
} STEREO_RHO_CEN_56_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_114:16;
		unsigned int f_rho_ham_dis_115:16;
	};
} STEREO_RHO_CEN_57_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_116:16;
		unsigned int f_rho_ham_dis_117:16;
	};
} STEREO_RHO_CEN_58_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_118:16;
		unsigned int f_rho_ham_dis_119:16;
	};
} STEREO_RHO_CEN_59_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_120:16;
		unsigned int f_rho_ham_dis_121:16;
	};
} STEREO_RHO_CEN_60_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_122:16;
		unsigned int f_rho_ham_dis_123:16;
	};
} STEREO_RHO_CEN_61_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_124:16;
		unsigned int f_rho_ham_dis_125:16;
	};
} STEREO_RHO_CEN_62_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rho_ham_dis_126:16;
		unsigned int f_rho_ham_dis_127:16;
	};
} STEREO_RHO_CEN_63_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rtl_version:32;
	};
} STEREO_SDP_HW_INFO_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_addr_vld:1;
		unsigned int reserved0:31;
	};
} STEREO_FRAME_START_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_sdp_top_soft_reset:1;
		unsigned int f_finish:1;
		unsigned int reserved0:30;
	};
} STEREO_SOFT_RESET_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_depth_w:1;
		unsigned int reserved0:31;
	};
} STEREO_sdp_irq_mask_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_finish_num:3;
		unsigned int reserved0:29;
	};
} STEREO_sdp_frm_status_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_rest_num:3;
		unsigned int reserved0:29;
	};
} STEREO_sdp_addr_status_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int reserved0:4;
		unsigned int f_max_burst_len:8;
		unsigned int f_max_ost_cnt:4;
		unsigned int reserved1:16;
	};
} STEREO_lf_r_cfg_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_start_addr_lo:32;
	};
} STEREO_lf_r_addr_lo_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_start_addr_hi:4;
		unsigned int reserved0:28;
	};
} STEREO_lf_r_addr_hi_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int reserved0:4;
		unsigned int f_max_burst_len:8;
		unsigned int f_max_ost_cnt:4;
		unsigned int reserved1:16;
	};
} STEREO_rf_r_cfg_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_start_addr_lo:32;
	};
} STEREO_rf_r_addr_lo_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_start_addr_hi:4;
		unsigned int reserved0:28;
	};
} STEREO_rf_r_addr_hi_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int reserved0:4;
		unsigned int f_max_burst_len:8;
		unsigned int f_max_ost_cnt:4;
		unsigned int reserved1:16;
	};
} STEREO_tofd_r_cfg_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_start_addr_lo:32;
	};
} STEREO_tofd_r_addr_lo_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_start_addr_hi:4;
		unsigned int reserved0:28;
	};
} STEREO_tofd_r_addr_hi_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int reserved0:4;
		unsigned int f_max_burst_len:8;
		unsigned int f_max_ost_cnt:4;
		unsigned int reserved1:16;
	};
} STEREO_tofc_r_cfg_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_start_addr_lo:32;
	};
} STEREO_tofc_r_addr_lo_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_start_addr_hi:4;
		unsigned int reserved0:28;
	};
} STEREO_tofc_r_addr_hi_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int reserved0:4;
		unsigned int f_max_burst_len:8;
		unsigned int f_max_ost_cnt:4;
		unsigned int reserved1:16;
	};
} STEREO_depth_w_cfg_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_start_addr_lo:32;
	};
} STEREO_depth_w_addr_lo_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_start_addr_hi:4;
		unsigned int reserved0:28;
	};
} STEREO_depth_w_addr_hi_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_width:16;
		unsigned int f_height:16;
	};
} STEREO_img_fram_cfg_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_hsgr_en:1;
		unsigned int f_vsgr_en:1;
		unsigned int reserved0:30;
	};
} STEREO_img_fram_cfg_1_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_hsgr_count:16;
		unsigned int f_vsgr_count:16;
	};
} STEREO_img_fram_cfg_2_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_first_interval:16;
		unsigned int f_interfval:16;
	};
} STEREO_img_hsgr_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_first_interval:16;
		unsigned int f_interfval:16;
	};
} STEREO_img_vsgr_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_width:16;
		unsigned int f_height:16;
	};
} STEREO_tof_fram_cfg_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_hsgr_en:1;
		unsigned int f_vsgr_en:1;
		unsigned int reserved0:30;
	};
} STEREO_tof_fram_cfg_1_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_hsgr_count:16;
		unsigned int f_vsgr_count:16;
	};
} STEREO_tof_fram_cfg_2_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_first_interval:16;
		unsigned int f_interfval:16;
	};
} STEREO_tof_hsgr_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_first_interval:16;
		unsigned int f_interfval:16;
	};
} STEREO_tof_vsgr_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_hdsr_en:1;
		unsigned int f_vdsr_en:1;
		unsigned int reserved0:30;
	};
} STEREO_dis_fram_cfg_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_hdsr_count:16;
		unsigned int f_vdsr_count:16;
	};
} STEREO_dis_fram_cfg_1_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_first_interval:16;
		unsigned int f_interfval:16;
	};
} STEREO_dis_hdsr_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_first_interval:16;
		unsigned int f_interfval:16;
	};
} STEREO_dis_vdsr_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_lf_r:4;
		unsigned int f_rf_r:4;
		unsigned int f_rr_r:4;
		unsigned int f_tofc_r:4;
		unsigned int f_tofd_r:4;
		unsigned int f_fr_r:4;
		unsigned int reserved0:8;
	};
} STEREO_rqos_cfg_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_fw_w:4;
		unsigned int f_rw_w:4;
		unsigned int f_depth_w:4;
		unsigned int reserved0:20;
	};
} STEREO_wqos_cfg_RBUS;

#ifdef SDP_CRC_VERSION
typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_lf:8;
		unsigned int f_rf:8;
		unsigned int f_td:8;
		unsigned int f_tc:8;
	};
} STEREO_rd_crc_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_depth:16;
		unsigned int reserved0:16;
	};
} STEREO_wr_crc_RBUS;
#endif

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_cr_axis_bridge_en:1;
		unsigned int f_cr_axis_mst_en:1;
		unsigned int f_cr_axis_slv_en:1;
		unsigned int f_cr_pixel_size_mode:1;
		unsigned int reserved0:28;
	};
} STEREO_FWRR_CTRL_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_cr_fw_arst:1;
		unsigned int reserved0:7;
		unsigned int f_cr_axis_mst_mem_read_en:1;
		unsigned int f_cr_axis_slv_mem_write_en:1;
		unsigned int f_cr_axis_mst_mem_read_done_clr:1;
		unsigned int f_cr_axis_slv_mem_write_done_clr:1;
		unsigned int reserved1:20;
	};
} STEREO_FWRR_CTRL_1_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_sr_axis_mst_fifo_full:1;
		unsigned int f_sr_axis_mst_fifo_empty:1;
		unsigned int f_sr_axis_slv_fifo_full:1;
		unsigned int f_sr_axis_slv_fifo_empty:1;
		unsigned int reserved0:4;
		unsigned int f_sr_axis_mst_err:1;
		unsigned int f_sr_axis_slv_err:1;
		unsigned int f_sr_axi_mst_err:1;
		unsigned int reserved1:5;
		unsigned int f_sr_axis_mst_mem_read_done:1;
		unsigned int f_sr_axis_slv_mem_write_done:1;
		unsigned int reserved2:14;
	};
} STEREO_FWRR_STATUS_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_cr_slv_waddr_base:32;
	};
} STEREO_FWRR_MEM_ADDR_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_cr_slv_raddr_base:32;
	};
} STEREO_FWRR_MEM_ADDR_1_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_cr_axis_bridge_en:1;
		unsigned int f_cr_axis_mst_en:1;
		unsigned int f_cr_axis_slv_en:1;
		unsigned int f_cr_pixel_size_mode:1;
		unsigned int reserved0:28;
	};
} STEREO_RWFR_CTRL_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_cr_fw_arst:1;
		unsigned int reserved0:7;
		unsigned int f_cr_axis_mst_mem_read_en:1;
		unsigned int f_cr_axis_slv_mem_write_en:1;
		unsigned int f_cr_axis_mst_mem_read_done_clr:1;
		unsigned int f_cr_axis_slv_mem_write_done_clr:1;
		unsigned int reserved1:20;
	};
} STEREO_RWFR_CTRL_1_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_sr_axis_mst_fifo_full:1;
		unsigned int f_sr_axis_mst_fifo_empty:1;
		unsigned int f_sr_axis_slv_fifo_full:1;
		unsigned int f_sr_axis_slv_fifo_empty:1;
		unsigned int reserved0:4;
		unsigned int f_sr_axis_mst_err:1;
		unsigned int f_sr_axis_slv_err:1;
		unsigned int f_sr_axi_mst_err:1;
		unsigned int reserved1:5;
		unsigned int f_sr_axis_mst_mem_read_done:1;
		unsigned int f_sr_axis_slv_mem_write_done:1;
		unsigned int reserved2:14;
	};
} STEREO_RWFR_STATUS_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_cr_slv_waddr_base:32;
	};
} STEREO_RWFR_MEM_ADDR_0_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_cr_slv_raddr_base:32;
	};
} STEREO_RWFR_MEM_ADDR_1_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_cr_slv_waddr_base_hi:1;
		unsigned int reserved0:31;
	};
} STEREO_FWRR_MEM_ADDR_2_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_cr_slv_raddr_base_hi:1;
		unsigned int reserved0:31;
	};
} STEREO_FWRR_MEM_ADDR_3_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_cr_slv_waddr_base_hi:1;
		unsigned int reserved0:31;
	};
} STEREO_RWFR_MEM_ADDR_2_RBUS;

typedef union {
	unsigned int RegValue;
	struct {
		unsigned int f_cr_slv_raddr_base_hi:1;
		unsigned int reserved0:31;
	};
} STEREO_RWFR_MEM_ADDR_3_RBUS;

#endif
