# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the sunplus SoC media device drivers.
#

obj-y += display/sp7350/
obj-y += mipicsi/
obj-$(CONFIG_VIDEO_SUNPLUS_GDC)		+= gdc/
obj-$(CONFIG_VIDEO_SUNPLUS_ISP_DRV)	+= isp/
obj-$(CONFIG_STEREO_SUNPLUS_DRV)	+= stereo/
obj-$(CONFIG_TSP_SUNPLUS_DRV)		+= tsp/
