snd-soc-spaudio-1-objs := sunplus_audio.o cpu_dai.o spsoc_tdm.o spsoc_util.o aud_hw.o
snd-soc-codec-2-objs := aud_codec.o
snd-soc-pcm-3-objs := spsoc_pcm.o
snd-soc-aud-4-objs := spsoc_aud.o

obj-$(CONFIG_SND_SOC_AUD_SP7350) += snd-soc-spaudio-1.o
obj-$(CONFIG_SND_SOC_AUD_SP7350) += snd-soc-codec-2.o
obj-$(CONFIG_SND_SOC_AUD_SP7350) += snd-soc-pcm-3.o
obj-$(CONFIG_SND_SOC_AUD_SP7350) += snd-soc-aud-4.o
