snd-soc-spaudio-1-objs := sunplus_audio.o cpu_dai.o spsoc_tdm.o spsoc_util.o aud_hw.o
snd-soc-pcm-2-objs := spsoc_pcm.o
snd-soc-aud-3-objs := spsoc_aud.o

obj-$(CONFIG_SND_SOC_AUD_SP7350) += snd-soc-spaudio-1.o
obj-$(CONFIG_SND_SOC_AUD_SP7350) += snd-soc-pcm-2.o
obj-$(CONFIG_SND_SOC_AUD_SP7350) += snd-soc-aud-3.o
